apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket
  title: Create an S3 Bucket
  description: Create an s3 bucket to deploy your application
  tags: ['recommended']
spec:
  owner: Athira-work
  type: service
  parameters:
    - title: S3 Bucket Creation
      required:
         - BucketName
         - Region
         - action    
      properties:
        BucketName:
          title: Bucket Name.
          type: string
          description: Name of the Bucket to be created.
          ui:autofocus: true
          ui:options:
            rows: 5

        Region:
          title:  AWS Region
          type: string
          description: Name of the region where you want to create your s3 bucket eg:- us-east-1, ap-south-1 etc.

        
        action:
          title: action
          type: string
          description: What action do you want to perform? Create or delete?
          enum:
            - apply
            - destroy

    - title: Choose a Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Location of the repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
# Getting the all the files/details from the template
    - id: fetch-base
      name: Fetching Details from content folder
      action: fetch:template
      input:
        url: ./  # Location of the content directory where catlog-info.yaml file is present for the template
        values:
          name: 
          

# Publish the content of the current working directory to our github directory
    - id: publish
      name: Publishing Details
      action: publish:github
      input:
       allowedHosts: ['github.com']
       description: This repo is to create an s3 bucket  using backstage.
       repoUrl: 
       repoVisibility: public # or 'internal' or 'private'
       # defaultBranch: master

# Triggering CI-CD to create resource in our case github action. 
    - id: github-action
      name: Starting GitHub action
      action: github:actions:dispatch
      input:
        workflowId:  .github/workflows/workflow.yml # ID of GitHub action WorkFlow
        repoUrl: 'github.com?repo=Terraform-s3&owner=Athira-work'
        branchOrTagName: 'main'
        workflowInputs:
          bucketName: 
          awsRegion: 
          action: 

# Registering new component in the catalog of backstage.
    - id: register
      name: Registering the new Component 
      action: catalog:register
      input:
        repoContentsUrl: 
        catalogInfoPath: '/content/catalog-info.yaml' # where the info of the catalog is stored.

# Output links  are displayed to the user after the template execution.
  output:
    links:
      - title: Repository
        url: 
      - title: Open in catalog
        icon: catalog
        entityRef: 
