apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstages3test"
  annotations:
    github.com/project-slug: Athira-work/Terraform-s3 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  title: 'S3 Automation' # you can give any title
  description: An example of s3 Creation. # Change Description accordingly
spec:
  type: service
  owner: Athira-work:Athira-work
  lifecycle: experimental

